<a href="https://colab.research.google.com/github/AlfonsoAngel/IntroductionToMachineLearning/blob/main/tensores1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import numpy as np

# Trabajando con tensores


In [2]:
torch.__version__

'1.6.0+cu101'

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [5]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[4.8579e-37, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.8782, 0.1178],
        [0.6580, 0.5803]])

In [6]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.8900, 0.0131],
        [0.2304, 0.8308]])

In [8]:
result = tensor_b + tensor_c
result

tensor([[1.7681, 0.1309],
        [0.8884, 1.4111]])

In [10]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.7681],
        [0.1309],
        [0.8884],
        [1.4111]])

In [16]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [17]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [18]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [20]:
tensor_x = torch.tensor([1,2,3,4])
#tensor_x, torch.unsqueeze(tensor_x,0)
tensor_x, torch.unsqueeze(tensor_x,1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [24]:
numpyArray = np.random.rand(2,2)
torch.from_numpy(numpyArray)

tensor([[0.6929, 0.3701],
        [0.5687, 0.4328]], dtype=torch.float64)